### GET all posts
GET http://127.0.0.1:8080/drawings
Accept: application/json

### GET post by user ID
GET http://127.0.0.1:8080/drawings/user/tq9NwzxdyjfkMOOP8tEsLkoQLdC3/history
Accept: application/json

### GET feed by user ID
GET http://127.0.0.1:8080/drawings/user/jn1vVoFvM0dUbcpMR29BtpoJ0yN2/feed
Accept: application/json

### POST create a new drawing
POST http://127.0.0.1:8080/drawings/create
Content-Type: application/json

{
  "creatorId": "tq9NwzxdyjfkMOOP8tEsLkoQLdC3",
  "title": "My Drawing 4",
  "imagePath": "file:///storage/emulated/0/Android/data/com.cs6018.canvasexample/files/Pictures/2023-10-27_001326.jpg"
}

### GET drawing by ID
GET http://127.0.0.1:8080/drawings/drawing/1
Accept: application/json

### PUT update drawing by ID
PUT http://127.0.0.1:8080/drawings/drawing/1
Content-Type: application/json

{
  "creatorId": "tq9NwzxdyjfkMOOP8tEsLkoQLdC3",
  "title": "My Drawing 4 updated",
  "imagePath": "file:///storage/emulated/0/Android/data/com.cs6018.canvasexample/files/Pictures/2023-10-27_001326.jpg"
}

### DELETE drawing by ID
DELETE http://127.0.0.1:8080/drawings/drawing/1
Accept: application/json

